apiVersion: v1
kind: Service
metadata:
  name: app_php
  labels:
    app: app_php
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: app_php
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_php
  labels:
    app: app_php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_php
  template:
    metadata:
      labels:
        app: app_php
    spec:
      containers:
      - image: sihemkh/app-pfe:v1
        name: app_php
        env:
        - name: MARIADB_HOST
          value: "mysql-data"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_DATABASE
          value: "testing"
        - name: MARIADB_USER
          value: "user"
        - name: MARIADB_PASSWORD
          value: "12345"
        ports:
        - containerPort: 80
          name: app_php