---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysqli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-glpi
        env:
        - name: MYSQL_DATABASE
          value: "testing"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "12345"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-glpi-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-glpi-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim